### ISSUE TITLE
exported images with huge grey squares

### ISSUE THREAD

**Issue by lares999** [MesseBasseProduction/MapPoster#1]
Hi
Thanks for your efforts! Great to display those maps!
When I export an image (all data formats) there are always grey squares in some sort of shape.
exported maps on [www.messebasseproduction.github.io/MapPoster/index.html](url)
![Signal Iduna Park](https://user-images.githubusercontent.com/118911814/203571029-405c728b-1ed0-49af-86bf-ced22b3c25d0.jpg)

Is that website not to use and better self-host?
Thanks!

**Comment by lares999** [comment]
OK, so when I host it, it works. Closing that issue.

**Comment by ArthurBeaulieu** [comment]
Ok thanks for the insight. I already went through this issue when exporting with a high resolution, tileloaded event is fired even tho not all tiles are loaded. Good to know that it's better on localhost, I'll try to improve this in the future, thanks for the feedback Iares999

**Comment by ArthurBeaulieu** [comment]
Don't apologize, you're welcome to raise issues! This app is far from being bullet proof so any feedback is great
I can reproduce, must admit I didn't catch the black shadow applied on output. I'll try to have a look to fix this, can you open another issue to track this topic ? Again, many thanks :)

**Comment by lares999** [comment]
Cool, thx! :)

**Comment by ArthurBeaulieu** [comment]
I've added bigger timeouts on tiles loading, it may (or not) fix the issue. I'll also conduct tests while throttling network to see if this could be this issue's origin.
