### ISSUE TITLE
UI translation

### ISSUE THREAD

**Issue by ArthurBeaulieu** [MesseBasseProduction/MapPoster#2]
At first en/fr

**Comment by lares999** [comment]
Shall I post here? Word by word from UI in english? Or how you wanna have it?

**Comment by ArthurBeaulieu** [comment]
I'll make a quick update to the code so it handle translation in a json file, do you want me to let you know when those internationalization files are up N?

**Comment by ArthurBeaulieu** [comment]
lang files can be retrieved in `asserts/nls/**.json`
I've made basic translation but feel free to improve it !

**Comment by lares999** [comment]
Did the german translation. Found all english terms great!

**Comment by ArthurBeaulieu** [comment]
Ok nice! Waiting to merge your PR thanks :)

**Comment by lares999** [comment]
Thank YOU! ;)

**Comment by ArthurBeaulieu** [comment]
@Iares999 Can you make a pull request on the repository with your fork so I can integrate you german translations ?
