### ISSUE TITLE
Map-Transparency turning into gray in exported images

### ISSUE THREAD

**Issue by lares999** [MesseBasseProduction/MapPoster#3]
When I export, there is a gray scale on the bottom, where it's actually turning the map transparent. The Map is fading out there. It is not shown in the preview, but on all the exported images, at all resolutions and formats.
Exported image:
![M B P](https://user-images.githubusercontent.com/118911814/203583321-8ff95d30-e9a2-4156-b12c-daa6ff6dc2d2.png)
Same image as preview:
![screenshot](https://user-images.githubusercontent.com/118911814/203583529-a61e3715-422b-489a-9ad5-18de739e6e2d.png)

**Comment by ArthurBeaulieu** [comment]
This issue seems to be browser related. So far :
- Window FF : OK
- Window Chrome : KO
- Linux FF : KO
- Linux Chromium : KO 
You're on MacOS, can you try on Safari, FF and Chrome and give me results here so we can track down this highlight ? Thx

**Comment by lares999** [comment]
M1 MacOS Ventura 13.0.1 
- Safari: KO
- Chrome: KO
- FF: KO
- Chromium: KO

**Comment by ArthurBeaulieu** [comment]
Thanks, I'm having a look at it, I'll let you know

**Comment by ArthurBeaulieu** [comment]
Serms fixed on my side, Can you confirm ?

**Comment by lares999** [comment]
Yes, can confirm :)
Great!
Thank you!
